// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlO8F8r72BpRH2wYauRVxkvREH1tdLRYM',
    appId: '1:322706101645:android:29f68d29717d53a2bf59c4',
    messagingSenderId: '322706101645',
    projectId: 'docdoc-app-a76c8',
    storageBucket: 'docdoc-app-a76c8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCneaZp-Pkm3nPqwEadpZvJNVpnqvNEiZE',
    appId: '1:322706101645:ios:bad145dcce4099bdbf59c4',
    messagingSenderId: '322706101645',
    projectId: 'docdoc-app-a76c8',
    storageBucket: 'docdoc-app-a76c8.appspot.com',
    iosBundleId: 'com.example.docdocProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCneaZp-Pkm3nPqwEadpZvJNVpnqvNEiZE',
    appId: '1:322706101645:ios:bad145dcce4099bdbf59c4',
    messagingSenderId: '322706101645',
    projectId: 'docdoc-app-a76c8',
    storageBucket: 'docdoc-app-a76c8.appspot.com',
    iosBundleId: 'com.example.docdocProject',
  );
}
